#!/usr/bin/env python3
"""Generate SVG coverage maps from court registry data.

This script reads the court registry (generated by build_court_registry.py)
and generates interactive SVG maps showing scraper coverage for:
- State courts (continental US + Alaska/Hawaii/territories)
- Federal circuits

Usage:
    python -m scripts.generate_coverage_maps

Output:
    docs/source/_static/state_coverage.svg
    docs/source/_static/federal_coverage.svg
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import tomllib  # ty: ignore[unresolved-import]
except ImportError:
    import tomli as tomllib  # type: ignore[import-not-found,no-redef]

# Add project root to path for imports
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from jinja2 import Environment, FileSystemLoader  # noqa: E402

from scripts.svg_paths import (  # noqa: E402
    FEDERAL_CIRCUITS,
    STATE_NAMES,
    STATE_PATHS,
)


def coverage_to_grayscale(pct: float) -> str:
    """Convert coverage percentage to grayscale hex color.

    Args:
        pct: Coverage percentage as decimal (0.0 to 1.0).

    Returns:
        Hex color string from white (#FFFFFF at 0%) to black (#000000 at 100%).
    """
    # 0% = white (255), 100% = black (0)
    gray = int(255 * (1 - pct))
    return f"#{gray:02x}{gray:02x}{gray:02x}"


def load_registry() -> dict:
    """Load the court registry from TOML file."""
    registry_path = (
        PROJECT_ROOT / "docs" / "source" / "_generated" / "court_registry.toml"
    )
    if not registry_path.exists():
        print(f"Error: Registry not found at {registry_path}")
        print("Run 'python -m scripts.build_court_registry' first.")
        sys.exit(1)

    with open(registry_path, "rb") as f:
        return tomllib.load(f)


def build_state_map_data(registry: dict) -> dict:
    """Build data structure for state coverage map.

    Args:
        registry: The court registry dictionary.

    Returns:
        Dictionary with states, stats, and rendering configuration.
    """
    jurisdictions = registry.get("jurisdictions", {})
    stats = registry.get("stats", {})

    states: dict[str, dict] = {}

    for state_code, state_name in STATE_NAMES.items():
        # Get jurisdiction data (using state code as jurisdiction code)
        jur_data = jurisdictions.get(state_code, {})
        coverage_pct = jur_data.get("coverage_pct", 0.0)

        # Check if we have any data for this jurisdiction
        unknown = state_code not in jurisdictions

        states[state_code] = {
            "name": state_name,
            "path_data": STATE_PATHS.get(state_code, ""),
            "coverage_pct": round(coverage_pct * 100, 1),
            "fill_color": (
                coverage_to_grayscale(coverage_pct)
                if not unknown
                else "#FFFFFF"
            ),
            "unknown": unknown,
            "current": False,  # Will be set per-page
        }

    return {
        "states": states,
        "stats": stats,
        "contrast_stroke": "#FF6600",  # Orange for contrast against grayscale
    }


def build_federal_map_data(registry: dict) -> dict:
    """Build data structure for federal circuit coverage map.

    Args:
        registry: The court registry dictionary.

    Returns:
        Dictionary with circuits, states, stats, and rendering configuration.
    """
    jurisdictions = registry.get("jurisdictions", {})

    # Get federal jurisdiction data
    fed_data = jurisdictions.get("FED", {})

    # Calculate coverage per circuit based on federal court data
    # For now, we'll use the overall FED coverage for all circuits
    # In a more sophisticated implementation, we'd calculate per-circuit
    fed_coverage = fed_data.get("coverage_pct", 0.0)

    circuits: dict[str, dict] = {}

    for circuit_num, circuit_states in FEDERAL_CIRCUITS.items():
        circuits[circuit_num] = {
            "states": circuit_states,
            "coverage_pct": round(fed_coverage * 100, 1),
            "fill_color": coverage_to_grayscale(fed_coverage),
            "unknown": "FED" not in jurisdictions,
            "current": False,
        }

    # Circuit label positions (approximate centers)
    circuit_labels = {
        "1": {"x": 890, "y": 145},
        "2": {"x": 820, "y": 175},
        "3": {"x": 805, "y": 230},
        "4": {"x": 780, "y": 290},
        "5": {"x": 520, "y": 430},
        "6": {"x": 680, "y": 250},
        "7": {"x": 600, "y": 230},
        "8": {"x": 480, "y": 200},
        "9": {"x": 120, "y": 280},
        "10": {"x": 330, "y": 310},
        "11": {"x": 700, "y": 410},
        "DC": {"x": 820, "y": 260},
    }

    # State path data for rendering
    states = {code: {"path_data": path} for code, path in STATE_PATHS.items()}

    return {
        "circuits": circuits,
        "states": states,
        "circuit_labels": circuit_labels,
        "stats": {
            "federal_scrapers": len(
                [
                    s
                    for s in registry.get("scrapers", {}).values()
                    if any(
                        c.startswith("ca") or c == "scotus"
                        for c in s["court_ids"]
                    )
                ]
            ),
            "federal_courts_known": fed_data.get("total_court_types", 0),
            "federal_courts_covered": fed_data.get("covered_court_types", 0),
        },
        "contrast_stroke": "#FF6600",
    }


def generate_maps() -> None:
    """Generate both coverage maps."""
    print("Generating coverage maps...")

    # Load registry
    registry = load_registry()

    # Set up Jinja2 environment
    template_dir = PROJECT_ROOT / "docs" / "source" / "_templates"
    output_dir = PROJECT_ROOT / "docs" / "source" / "_static"
    output_dir.mkdir(parents=True, exist_ok=True)

    env = Environment(
        loader=FileSystemLoader(str(template_dir)), autoescape=False
    )

    # Generate state coverage map
    state_data = build_state_map_data(registry)
    state_template = env.get_template("state_coverage.svg.jinja2")
    state_svg = state_template.render(**state_data)

    state_output = output_dir / "state_coverage.svg"
    with open(state_output, "w") as f:
        f.write(state_svg)
    print(f"  Wrote {state_output}")

    # Generate federal coverage map
    federal_data = build_federal_map_data(registry)
    federal_template = env.get_template("federal_coverage.svg.jinja2")
    federal_svg = federal_template.render(**federal_data)

    federal_output = output_dir / "federal_coverage.svg"
    with open(federal_output, "w") as f:
        f.write(federal_svg)
    print(f"  Wrote {federal_output}")

    print("Done!")


def main() -> int:
    """Main entry point."""
    try:
        generate_maps()
        return 0
    except Exception as e:
        print(f"Error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
